services:
  app1:
    build: .
    ports:
      - 3001:3000
    volumes:
      - files:/app/files
  app2:
    build: .
    ports:
      - 3002:3000
    volumes:
      - files:/app/files
  app3:
    build: .
    ports:
      - 3003:3000
    volumes:
      - files:/app/files
  server:
    image: nginx
    ports:
      - "8080:8080"
      - "80:80"

volumes:
  files:
